## 正常
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jigsaw
  name: jigsaw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jigsaw
  template:
    metadata:
      labels:
        app: jigsaw
    spec:
      serviceAccountName: prometheus
      containers:
        - name: jigsaw
          image: jigsaw:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: Asia/Shanghai
---

## 直接部署到集群外
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jigsaw
  name: jigsaw
  annotations:
    prometheus.io/port: '9009'
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/api/actuator/prometheus'
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      nodePort: 32010
  selector:
    app: jigsaw

